{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9439b6a1-9532-4d2c-8e20-971c08896173",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Adult Income — Feature Engineering and EDA Project\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# =========================\n",
    "# 1. Load Dataset\n",
    "# =========================\n",
    "df = pd.read_csv(\"adult.csv\")  # Replace with your dataset path\n",
    "print(\"Dataset Shape:\", df.shape)\n",
    "print(\"\\nColumn Names:\", df.columns.tolist())\n",
    "print(df.head())\n",
    "\n",
    "# =========================\n",
    "# 2. Handle Missing Values\n",
    "# =========================\n",
    "# Replace '?' with NaN\n",
    "df.replace(\"?\", np.nan, inplace=True)\n",
    "\n",
    "# Show missing values\n",
    "print(\"\\nMissing Values:\\n\", df.isnull().sum())\n",
    "\n",
    "# Drop rows with missing values (or impute if preferred)\n",
    "df.dropna(inplace=True)\n",
    "print(\"Shape after cleaning:\", df.shape)\n",
    "\n",
    "# =========================\n",
    "# 3. Feature Engineering\n",
    "# =========================\n",
    "# Create AgeGroup feature\n",
    "df[\"AgeGroup\"] = pd.cut(\n",
    "    df[\"age\"],\n",
    "    bins=[0, 25, 40, 60, 100],\n",
    "    labels=[\"Young\", \"Adult\", \"Middle-Aged\", \"Senior\"]\n",
    ")\n",
    "\n",
    "# Create WorkHoursCategory feature\n",
    "df[\"WorkHoursCategory\"] = pd.cut(\n",
    "    df[\"hours-per-week\"],\n",
    "    bins=[0, 20, 40, 60, 100],\n",
    "    labels=[\"Part-time\", \"Full-time\", \"Overtime\", \"Extreme\"]\n",
    ")\n",
    "\n",
    "# Create FamilySize feature\n",
    "df[\"FamilySize\"] = df[\"fnlwgt\"] / 1000  # proxy using fnlwgt\n",
    "\n",
    "# Encode categorical variables\n",
    "categorical_cols = df.select_dtypes(include=\"object\").columns\n",
    "for col in categorical_cols:\n",
    "    df[col] = df[col].astype(\"category\").cat.codes\n",
    "\n",
    "print(\"\\nFeature Engineering Completed. New Columns Added:\")\n",
    "print([\"AgeGroup\", \"WorkHoursCategory\", \"FamilySize\"])\n",
    "\n",
    "# =========================\n",
    "# 4. Exploratory Data Analysis (EDA)\n",
    "# =========================\n",
    "# Income distribution\n",
    "sns.countplot(data=df, x=\"income\")\n",
    "plt.title(\"Income Distribution\")\n",
    "plt.show()\n",
    "\n",
    "# Age vs Income\n",
    "sns.histplot(data=df, x=\"age\", hue=\"income\", bins=30, kde=True)\n",
    "plt.title(\"Age vs Income\")\n",
    "plt.show()\n",
    "\n",
    "# Education vs Income\n",
    "sns.countplot(data=df, x=\"education\", hue=\"income\")\n",
    "plt.xticks(rotation=90)\n",
    "plt.title(\"Education vs Income\")\n",
    "plt.show()\n",
    "\n",
    "# Gender vs Income\n",
    "sns.countplot(data=df, x=\"sex\", hue=\"income\")\n",
    "plt.title(\"Gender vs Income\")\n",
    "plt.show()\n",
    "\n",
    "# Work Hours vs Income\n",
    "sns.boxplot(data=df, x=\"income\", y=\"hours-per-week\")\n",
    "plt.title(\"Work Hours vs Income\")\n",
    "plt.show()\n",
    "\n",
    "# Correlation Heatmap\n",
    "plt.figure(figsize=(12,8))\n",
    "sns.heatmap(df.corr(), annot=True, cmap=\"coolwarm\", fmt=\".2f\")\n",
    "plt.title(\"Correlation Heatmap\")\n",
    "plt.show()\n",
    "\n",
    "# =========================\n",
    "# 5. Save Cleaned Dataset\n",
    "# =========================\n",
    "df.to_csv(\"adult_cleaned.csv\", index=False)\n",
    "print(\"\\nCleaned dataset saved as 'adult_cleaned.csv'\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
