{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9600bb9a-128b-42fd-bd69-e378082ec4c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Auto MPG — Linear Regression, Feature Scaling, and Encoding Project\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import mean_squared_error, r2_score\n",
    "\n",
    "# =========================\n",
    "# 1. Load Dataset\n",
    "# =========================\n",
    "df = pd.read_csv(\"auto-mpg.csv\")  # Replace with your dataset path\n",
    "print(\"Dataset Shape:\", df.shape)\n",
    "print(\"\\nColumn Names:\", df.columns.tolist())\n",
    "print(df.head())\n",
    "\n",
    "# =========================\n",
    "# 2. Exploratory Data Analysis (EDA)\n",
    "# =========================\n",
    "# Distribution of MPG\n",
    "sns.histplot(df[\"mpg\"], bins=20, kde=True)\n",
    "plt.title(\"MPG Distribution\")\n",
    "plt.show()\n",
    "\n",
    "# Horsepower vs MPG\n",
    "sns.scatterplot(data=df, x=\"horsepower\", y=\"mpg\")\n",
    "plt.title(\"Horsepower vs MPG\")\n",
    "plt.show()\n",
    "\n",
    "# Correlation heatmap\n",
    "plt.figure(figsize=(10,6))\n",
    "sns.heatmap(df.corr(numeric_only=True), annot=True, cmap=\"coolwarm\")\n",
    "plt.title(\"Correlation Heatmap\")\n",
    "plt.show()\n",
    "\n",
    "# =========================\n",
    "# 3. Data Cleaning\n",
    "# =========================\n",
    "# Replace missing values represented as '?'\n",
    "df.replace(\"?\", np.nan, inplace=True)\n",
    "\n",
    "# Convert horsepower to numeric\n",
    "df[\"horsepower\"] = pd.to_numeric(df[\"horsepower\"], errors=\"coerce\")\n",
    "\n",
    "# Drop rows with missing values\n",
    "df.dropna(inplace=True)\n",
    "\n",
    "# =========================\n",
    "# 4. Features and Target\n",
    "# =========================\n",
    "X = df.drop([\"mpg\", \"car name\"], axis=1)\n",
    "y = df[\"mpg\"]\n",
    "\n",
    "# Identify categorical and numerical features\n",
    "categorical_features = [\"origin\"]\n",
    "numerical_features = [col for col in X.columns if col not in categorical_features]\n",
    "\n",
    "# =========================\n",
    "# 5. Preprocessing Pipeline\n",
    "# =========================\n",
    "# One-hot encode categorical features, scale numerical features\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        (\"num\", StandardScaler(), numerical_features),\n",
    "        (\"cat\", OneHotEncoder(), categorical_features)\n",
    "    ]\n",
    ")\n",
    "\n",
    "# Build pipeline with preprocessing + regression\n",
    "pipeline = Pipeline([\n",
    "    (\"preprocessor\", preprocessor),\n",
    "    (\"regressor\", LinearRegression())\n",
    "])\n",
    "\n",
    "# =========================\n",
    "# 6. Train-Test Split\n",
    "# =========================\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "# =========================\n",
    "# 7. Model Training\n",
    "# =========================\n",
    "pipeline.fit(X_train, y_train)\n",
    "\n",
    "# Predictions\n",
    "y_pred = pipeline.predict(X_test)\n",
    "\n",
    "# =========================\n",
    "# 8. Evaluation\n",
    "# =========================\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "rmse = np.sqrt(mse)\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(\"\\nModel Performance:\")\n",
    "print(\"MSE:\", mse)\n",
    "print(\"RMSE:\", rmse)\n",
    "print(\"R² Score:\", r2)\n",
    "\n",
    "# =========================\n",
    "# 9. Visualization of Predictions\n",
    "# =========================\n",
    "plt.figure(figsize=(8,6))\n",
    "plt.scatter(y_test, y_pred, color=\"blue\", alpha=0.6)\n",
    "plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], \"r--\")\n",
    "plt.xlabel(\"Actual MPG\")\n",
    "plt.ylabel(\"Predicted MPG\")\n",
    "plt.title(\"Actual vs Predicted MPG\")\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
