{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e3a7f5ce-459d-4cd7-b368-de871f17f344",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "First 5 rows:\n",
      "   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \\\n",
      "0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   \n",
      "1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   \n",
      "2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   \n",
      "3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   \n",
      "4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   \n",
      "\n",
      "   Longitude  \n",
      "0    -122.23  \n",
      "1    -122.22  \n",
      "2    -122.24  \n",
      "3    -122.25  \n",
      "4    -122.25  \n",
      "\n",
      "Column names:\n",
      "Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',\n",
      "       'Latitude', 'Longitude'],\n",
      "      dtype='object')\n",
      "\n",
      "Target column:\n",
      "MedHouseVal\n",
      "\n",
      "Input features:\n",
      "['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']\n",
      "\n",
      "Target:\n",
      "MedHouseVal\n",
      "\n",
      "Numerical columns:\n",
      "['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']\n",
      "\n",
      "========\n",
      "LINEAR REGRESSION\n",
      "========\n",
      "\n",
      "Intercept:\n",
      "2.0719469373788777\n",
      "\n",
      "Coefficients:\n",
      "      Feature  Coefficient\n",
      "0      MedInc     0.854383\n",
      "1    HouseAge     0.122546\n",
      "2    AveRooms    -0.294410\n",
      "3   AveBedrms     0.339259\n",
      "4  Population    -0.002308\n",
      "5    AveOccup    -0.040829\n",
      "6    Latitude    -0.896929\n",
      "7   Longitude    -0.869842\n",
      "\n",
      "========\n",
      "RIDGE REGRESSION - L2\n",
      "========\n",
      "\n",
      "Alpha:\n",
      "1.0\n",
      "\n",
      "Intercept:\n",
      "2.0719469373788777\n",
      "\n",
      "Coefficients:\n",
      "      Feature  Coefficient\n",
      "0      MedInc     0.854327\n",
      "1    HouseAge     0.122624\n",
      "2    AveRooms    -0.294210\n",
      "3   AveBedrms     0.339008\n",
      "4  Population    -0.002282\n",
      "5    AveOccup    -0.040833\n",
      "6    Latitude    -0.896168\n",
      "7   Longitude    -0.869071\n",
      "\n",
      "========\n",
      "LASSO REGRESSION - L1\n",
      "========\n",
      "\n",
      "Alpha:\n",
      "0.01\n",
      "\n",
      "Intercept:\n",
      "2.0719469373788773\n",
      "\n",
      "Coefficients:\n",
      "      Feature  Coefficient\n",
      "0      MedInc     0.800957\n",
      "1    HouseAge     0.127087\n",
      "2    AveRooms    -0.162759\n",
      "3   AveBedrms     0.206207\n",
      "4  Population    -0.000000\n",
      "5    AveOccup    -0.030602\n",
      "6    Latitude    -0.790113\n",
      "7   Longitude    -0.755674\n",
      "\n",
      "========\n",
      "ELASTIC NET\n",
      "========\n",
      "\n",
      "Alpha:\n",
      "0.01\n",
      "\n",
      "L1 Ratio:\n",
      "0.5\n",
      "\n",
      "Intercept:\n",
      "2.0719469373788773\n",
      "\n",
      "Coefficients:\n",
      "      Feature  Coefficient\n",
      "0      MedInc     0.823963\n",
      "1    HouseAge     0.130005\n",
      "2    AveRooms    -0.216074\n",
      "3   AveBedrms     0.256299\n",
      "4  Population    -0.000000\n",
      "5    AveOccup    -0.035948\n",
      "6    Latitude    -0.788420\n",
      "7   Longitude    -0.757036\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.linear_model import (\n",
    "    LinearRegression,\n",
    "    Ridge,\n",
    "    Lasso,\n",
    "    ElasticNet\n",
    ")\n",
    "from sklearn.datasets import fetch_california_housing\n",
    "#1. LOAD CSV FILE\n",
    "df = pd.read_csv(\"california_housing.csv\")\n",
    "print(\"First 5 rows:\")\n",
    "print(df.head())\n",
    "print(\"\\nColumn names:\")\n",
    "print(df.columns)\n",
    "#2. REMOVE MISSING VALUES\n",
    "df = df.dropna()\n",
    "#===========\n",
    "#3. LOAD TARGET VALUES\n",
    "#============\n",
    "housing = fetch_california_housing()\n",
    "y = pd.Series(\n",
    "    housing.target,\n",
    "    name=\"MedHouseVal\"\n",
    ")\n",
    "print(\"\\nTarget column:\")\n",
    "print(\"MedHouseVal\")\n",
    "#============\n",
    "#4. SEPARATE INPUT AND TARGET\n",
    "#============\n",
    "X = df.copy()\n",
    "print(\"\\nInput features:\")\n",
    "print(X.columns.tolist())\n",
    "print(\"\\nTarget:\")\n",
    "print(\"MedHouseVal\")\n",
    "#============\n",
    "#5. IDENTIFY NUMERICAL AND CATEGORICAL COLUMNS\n",
    "#============\n",
    "numerical_columns = X.select_dtypes(\n",
    "    include=[\"int64\", \"float64\"]\n",
    ").columns\n",
    "print(\"\\nNumerical columns:\")\n",
    "print(numerical_columns.tolist())\n",
    "#============\n",
    "#6. TRAIN-TEST SPLIT\n",
    "#============\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X,\n",
    "    y,\n",
    "    test_size=0.2,\n",
    "    random_state=42\n",
    ")\n",
    "#============\n",
    "#7. PREPROCESSING\n",
    "#============\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "#============\n",
    "#8. LINEAR REGRESSION\n",
    "#============\n",
    "linear_model = LinearRegression()\n",
    "linear_model.fit(X_train, y_train)\n",
    "print(\"\\n========\")\n",
    "print(\"LINEAR REGRESSION\")\n",
    "print(\"========\")\n",
    "print(\"\\nIntercept:\")\n",
    "print(linear_model.intercept_)\n",
    "print(\"\\nCoefficients:\")\n",
    "linear_coefficients = pd.DataFrame({\n",
    "    \"Feature\": numerical_columns,\n",
    "    \"Coefficient\": linear_model.coef_\n",
    "})\n",
    "print(linear_coefficients)\n",
    "#============\n",
    "#9. RIDGE REGRESSION - L2\n",
    "#============\n",
    "ridge_model = Ridge(alpha=1.0)\n",
    "ridge_model.fit(X_train, y_train)\n",
    "print(\"\\n========\")\n",
    "print(\"RIDGE REGRESSION - L2\")\n",
    "print(\"========\")\n",
    "print(\"\\nAlpha:\")\n",
    "print(ridge_model.alpha)\n",
    "print(\"\\nIntercept:\")\n",
    "print(ridge_model.intercept_)\n",
    "print(\"\\nCoefficients:\")\n",
    "ridge_coefficients = pd.DataFrame({\n",
    "    \"Feature\": numerical_columns,\n",
    "    \"Coefficient\": ridge_model.coef_\n",
    "})\n",
    "print(ridge_coefficients)\n",
    "#============\n",
    "#10. LASSO REGRESSION - L1\n",
    "#============\n",
    "lasso_model = Lasso(alpha=0.01)\n",
    "lasso_model.fit(X_train, y_train)\n",
    "print(\"\\n========\")\n",
    "print(\"LASSO REGRESSION - L1\")\n",
    "print(\"========\")\n",
    "print(\"\\nAlpha:\")\n",
    "print(lasso_model.alpha)\n",
    "print(\"\\nIntercept:\")\n",
    "print(lasso_model.intercept_)\n",
    "print(\"\\nCoefficients:\")\n",
    "lasso_coefficients = pd.DataFrame({\n",
    "    \"Feature\": numerical_columns,\n",
    "    \"Coefficient\": lasso_model.coef_\n",
    "})\n",
    "print(lasso_coefficients)\n",
    "#============\n",
    "#11. ELASTIC NET\n",
    "#============\n",
    "elastic_model = ElasticNet(\n",
    "    alpha=0.01,\n",
    "    l1_ratio=0.5\n",
    ")\n",
    "elastic_model.fit(X_train, y_train)\n",
    "print(\"\\n========\")\n",
    "print(\"ELASTIC NET\")\n",
    "print(\"========\")\n",
    "print(\"\\nAlpha:\")\n",
    "print(elastic_model.alpha)\n",
    "print(\"\\nL1 Ratio:\")\n",
    "print(elastic_model.l1_ratio)\n",
    "print(\"\\nIntercept:\")\n",
    "print(elastic_model.intercept_)\n",
    "print(\"\\nCoefficients:\")\n",
    "elastic_coefficients = pd.DataFrame({\n",
    "    \"Feature\": numerical_columns,\n",
    "    \"Coefficient\": elastic_model.coef_\n",
    "})\n",
    "print(elastic_coefficients)\n",
    "#============\n",
    "#END\n",
    "#============"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8eebcda1-db39-49d6-8b66-716a17c55326",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
