{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "08a3a034-a919-4860-9875-381eb91cccf3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Before cleaning:\n",
      "   Patient_ID  Age Gender  Symptom_Score Gene_Mutation  Lab_Value  \\\n",
      "0       P001   34      F             12         BRCA1        145   \n",
      "1       P002   56      M              8           NaN        132   \n",
      "2       P003   41      F             15          CFTR        210   \n",
      "3       P004   29      M              7           NaN        120   \n",
      "4       P005   63      F             14         LRRK2        250   \n",
      "5       P006   52      M              9           NaN        140   \n",
      "6       P007   38      F             20           GBA        300   \n",
      "7       P008   45      M             10           NaN        135   \n",
      "8       P009   12      F             22         MECP2        280   \n",
      "9       P010   50      M             25           HTT        310   \n",
      "\n",
      "                Disease  \n",
      "0                Common  \n",
      "1                Common  \n",
      "2       Cystic Fibrosis  \n",
      "3                Common  \n",
      "4   Parkinsons (LRRK2)  \n",
      "5                Common  \n",
      "6       Gaucher Disease  \n",
      "7                Common  \n",
      "8         Rett Syndrome  \n",
      "9  Huntingtons Disease  \n",
      "\n",
      "Duplicate rows (exact matches):\n",
      " Empty DataFrame\n",
      "Columns: [Patient_ID, Age, Gender, Symptom_Score, Gene_Mutation, Lab_Value, Disease]\n",
      "Index: []\n",
      "\n",
      "Duplicate rows summary:\n",
      " False    30\n",
      "Name: count, dtype: int64\n",
      "\n",
      "After cleaning:\n",
      "   Patient_ID  Age Gender  Symptom_Score Gene_Mutation  Lab_Value  \\\n",
      "0       P001   34      F             12         BRCA1        145   \n",
      "1       P002   56      M              8       Unknown        132   \n",
      "2       P003   41      F             15          CFTR        210   \n",
      "3       P004   29      M              7       Unknown        120   \n",
      "4       P005   63      F             14         LRRK2        250   \n",
      "5       P006   52      M              9       Unknown        140   \n",
      "6       P007   38      F             20           GBA        300   \n",
      "7       P008   45      M             10       Unknown        135   \n",
      "8       P009   12      F             22         MECP2        280   \n",
      "9       P010   50      M             25           HTT        310   \n",
      "\n",
      "                Disease  \n",
      "0                Common  \n",
      "1                Common  \n",
      "2       Cystic Fibrosis  \n",
      "3                Common  \n",
      "4   Parkinsons (LRRK2)  \n",
      "5                Common  \n",
      "6       Gaucher Disease  \n",
      "7                Common  \n",
      "8         Rett Syndrome  \n",
      "9  Huntingtons Disease  \n",
      "\n",
      "Missing values after cleaning:\n",
      " Patient_ID       0\n",
      "Age              0\n",
      "Gender           0\n",
      "Symptom_Score    0\n",
      "Gene_Mutation    0\n",
      "Lab_Value        0\n",
      "Disease          0\n",
      "dtype: int64\n",
      "\n",
      "Duplicate rows after cleaning:\n",
      " 0\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Step 1: Load dataset\n",
    "df = pd.read_csv(\"DBSCAN_dataset.csv\", encoding=\"latin1\")\n",
    "\n",
    "# Step 2: Show first 10 rows before cleaning\n",
    "print(\"Before cleaning:\\n\", df.head(10))\n",
    "\n",
    "# Step 3: Find duplicate rows\n",
    "duplicates = df[df.duplicated()]\n",
    "print(\"\\nDuplicate rows (exact matches):\\n\", duplicates)\n",
    "\n",
    "# Step 4: Show duplicate summary (like missing values style)\n",
    "print(\"\\nDuplicate rows summary:\\n\", df.duplicated().value_counts())\n",
    "\n",
    "# Step 5: Replace NaN values\n",
    "# Simple approach: replace all NaN with \"Unknown\"\n",
    "df = df.fillna(\"Unknown\")\n",
    "\n",
    "# Step 6: Remove duplicates\n",
    "df = df.drop_duplicates()\n",
    "\n",
    "# Step 7: Show first 10 rows after cleaning\n",
    "print(\"\\nAfter cleaning:\\n\", df.head(10))\n",
    "\n",
    "# Step 8: Check if any NaN values remain\n",
    "print(\"\\nMissing values after cleaning:\\n\", df.isnull().sum())\n",
    "\n",
    "# Step 9: Final duplicate check after cleaning\n",
    "print(\"\\nDuplicate rows after cleaning:\\n\", df.duplicated().sum())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "444895da-beb1-4b57-a2a3-90ed061fd461",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
