{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52edea96-e5b2-4bcd-8ab6-5e2c0af17dd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Decision Trees — Splitting Criteria, CCP Pruning, and Depth Sweep\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.tree import DecisionTreeClassifier, plot_tree\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "# Load dataset\n",
    "df = pd.read_csv(\"placement_predict_50k_Dataset.csv\")\n",
    "print(\"Dataset Shape:\", df.shape)\n",
    "print(\"\\nColumn Names:\")\n",
    "print(df.columns.tolist())\n",
    "\n",
    "# Selecting X(features) and Y(target)\n",
    "X = df[['CGPA']]\n",
    "y = df['PlacementStatus']\n",
    "\n",
    "# Convert categorical target into numbers if required\n",
    "if y.dtype == 'object':\n",
    "    y = y.map({'Placed': 1, 'Not Placed': 0})\n",
    "\n",
    "# Remove missing values\n",
    "data = pd.concat([X, y], axis=1).dropna()\n",
    "X = data[['CGPA']]\n",
    "y = data['PlacementStatus']\n",
    "\n",
    "# Train-test split\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "# Gini criterion\n",
    "gini_tree = DecisionTreeClassifier(criterion='gini', random_state=42)\n",
    "gini_tree.fit(X_train, y_train)\n",
    "gini_pred = gini_tree.predict(X_test)\n",
    "gini_accuracy = accuracy_score(y_test, gini_pred)\n",
    "print(\"\\nGINI Accuracy:\", gini_accuracy)\n",
    "\n",
    "# Entropy criterion\n",
    "entropy_tree = DecisionTreeClassifier(criterion='entropy', random_state=42)\n",
    "entropy_tree.fit(X_train, y_train)\n",
    "entropy_pred = entropy_tree.predict(X_test)\n",
    "entropy_accuracy = accuracy_score(y_test, entropy_pred)\n",
    "print(\"Entropy Accuracy:\", entropy_accuracy)\n",
    "\n",
    "# CCP PRUNING\n",
    "path = gini_tree.cost_complexity_pruning_path(X_train, y_train)\n",
    "ccp_alphas = path.ccp_alphas\n",
    "print(\"\\nCCP Alpha Values:\")\n",
    "print(ccp_alphas)\n",
    "\n",
    "# Train trees with different CCP alpha values\n",
    "ccp_accuracies = []\n",
    "for alpha in ccp_alphas:\n",
    "    clf = DecisionTreeClassifier(criterion='gini', ccp_alpha=alpha, random_state=42)\n",
    "    clf.fit(X_train, y_train)\n",
    "    prediction = clf.predict(X_test)\n",
    "    accuracy = accuracy_score(y_test, prediction)\n",
    "    ccp_accuracies.append(accuracy)\n",
    "\n",
    "# Find best CCP alpha\n",
    "best_index = ccp_accuracies.index(max(ccp_accuracies))\n",
    "best_alpha = ccp_alphas[best_index]\n",
    "print(\"\\nBest CCP Alpha:\", best_alpha)\n",
    "print(\"Best CCP Accuracy:\", ccp_accuracies[best_index])\n",
    "\n",
    "# Train final pruned tree\n",
    "pruned_tree = DecisionTreeClassifier(\n",
    "    criterion='gini', ccp_alpha=best_alpha, random_state=42\n",
    ")\n",
    "pruned_tree.fit(X_train, y_train)\n",
    "\n",
    "# DEPTH SWEEP\n",
    "depths = range(1, 16)\n",
    "depth_accuracies = []\n",
    "for depth in depths:\n",
    "    tree = DecisionTreeClassifier(criterion='gini', max_depth=depth, random_state=42)\n",
    "    tree.fit(X_train, y_train)\n",
    "    prediction = tree.predict(X_test)\n",
    "    accuracy = accuracy_score(y_test, prediction)\n",
    "    depth_accuracies.append(accuracy)\n",
    "    print(\"Depth:\", depth, \" Accuracy:\", accuracy)\n",
    "\n",
    "# Find best depth\n",
    "best_depth_index = depth_accuracies.index(max(depth_accuracies))\n",
    "best_depth = list(depths)[best_depth_index]\n",
    "print(\"\\nBest Depth:\", best_depth)\n",
    "print(\"Best Depth Accuracy:\", depth_accuracies[best_depth_index])\n",
    "\n",
    "# Plot Depth Sweep\n",
    "plt.figure(figsize=(8, 5))\n",
    "plt.plot(list(depths), depth_accuracies, marker='o')\n",
    "plt.xlabel(\"Maximum Depth\")\n",
    "plt.ylabel(\"Accuracy\")\n",
    "plt.title(\"Decision Tree Depth Sweep\")\n",
    "plt.grid()\n",
    "plt.show()\n",
    "\n",
    "# Plot CCP Pruning\n",
    "plt.figure(figsize=(8, 5))\n",
    "plt.plot(ccp_alphas, ccp_accuracies, marker='o')\n",
    "plt.xlabel(\"CCP Alpha\")\n",
    "plt.ylabel(\"Accuracy\")\n",
    "plt.title(\"Cost Complexity Pruning\")\n",
    "plt.grid()\n",
    "plt.show()\n",
    "\n",
    "# VISUALIZATION of Final Tree\n",
    "final_tree = DecisionTreeClassifier(\n",
    "    criterion='gini', max_depth=best_depth, ccp_alpha=best_alpha, random_state=42\n",
    ")\n",
    "final_tree.fit(X_train, y_train)\n",
    "\n",
    "plt.figure(figsize=(15, 8))\n",
    "plot_tree(\n",
    "    final_tree,\n",
    "    feature_names=X.columns,\n",
    "    class_names=['Not Placed', 'Placed'],\n",
    "    filled=True,\n",
    "    rounded=True\n",
    ")\n",
    "plt.title(\"Final Pruned Decision Tree\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb67320e-a57c-4327-bd75-4b8342632a8f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
