{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ec343df-4b82-4ead-8c5b-c1b5564bad28",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Diabetes Severity — Multinomial Logistic Regression Project\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix, classification_report\n",
    "\n",
    "# =========================\n",
    "# 1. Load Dataset\n",
    "# =========================\n",
    "# Replace with your dataset path\n",
    "df = pd.read_csv(\"diabetes_severity.csv\")\n",
    "print(\"Dataset Shape:\", df.shape)\n",
    "print(\"\\nColumn Names:\", df.columns.tolist())\n",
    "print(df.head())\n",
    "\n",
    "# =========================\n",
    "# 2. Exploratory Data Analysis (EDA)\n",
    "# =========================\n",
    "# Severity distribution\n",
    "sns.countplot(data=df, x=\"Severity\")\n",
    "plt.title(\"Diabetes Severity Distribution\")\n",
    "plt.show()\n",
    "\n",
    "# Age vs Severity\n",
    "sns.boxplot(data=df, x=\"Severity\", y=\"Age\")\n",
    "plt.title(\"Age vs Diabetes Severity\")\n",
    "plt.show()\n",
    "\n",
    "# BMI vs Severity\n",
    "sns.boxplot(data=df, x=\"Severity\", y=\"BMI\")\n",
    "plt.title(\"BMI vs Diabetes Severity\")\n",
    "plt.show()\n",
    "\n",
    "# Correlation heatmap\n",
    "plt.figure(figsize=(10,6))\n",
    "sns.heatmap(df.corr(numeric_only=True), annot=True, cmap=\"coolwarm\")\n",
    "plt.title(\"Correlation Heatmap\")\n",
    "plt.show()\n",
    "\n",
    "# =========================\n",
    "# 3. Preprocessing\n",
    "# =========================\n",
    "# Drop missing values\n",
    "df = df.dropna()\n",
    "\n",
    "# Features and target\n",
    "X = df.drop(\"Severity\", axis=1)\n",
    "y = df[\"Severity\"]\n",
    "\n",
    "# Standardize features\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X)\n",
    "\n",
    "# Train-test split\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X_scaled, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "# =========================\n",
    "# 4. Model Training\n",
    "# =========================\n",
    "# Multinomial Logistic Regression\n",
    "log_reg = LogisticRegression(\n",
    "    multi_class=\"multinomial\",\n",
    "    solver=\"lbfgs\",\n",
    "    max_iter=1000,\n",
    "    random_state=42\n",
    ")\n",
    "log_reg.fit(X_train, y_train)\n",
    "\n",
    "# Predictions\n",
    "y_pred = log_reg.predict(X_test)\n",
    "\n",
    "# =========================\n",
    "# 5. Evaluation\n",
    "# =========================\n",
    "print(\"\\nAccuracy:\", accuracy_score(y_test, y_pred))\n",
    "print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))\n",
    "\n",
    "# Confusion Matrix\n",
    "cm = confusion_matrix(y_test, y_pred)\n",
    "sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\",\n",
    "            xticklabels=log_reg.classes_,\n",
    "            yticklabels=log_reg.classes_)\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.xlabel(\"Predicted\")\n",
    "plt.ylabel(\"Actual\")\n",
    "plt.show()\n",
    "\n",
    "# =========================\n",
    "# 6. Visualization of Coefficients\n",
    "# =========================\n",
    "coefficients = pd.DataFrame(\n",
    "    log_reg.coef_,\n",
    "    columns=X.columns,\n",
    "    index=log_reg.classes_\n",
    ")\n",
    "\n",
    "plt.figure(figsize=(12,6))\n",
    "sns.heatmap(coefficients, annot=True, cmap=\"coolwarm\")\n",
    "plt.title(\"Feature Importance by Severity Class (Logistic Regression Coefficients)\")\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
